# Generated by Django 4.2.16 on 2026-03-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_rutaparada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RutaParada',
        ),
    ]
