# Generated by Django 4.2.16 on 2026-03-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_delete_rutaparada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AliasParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alias', models.CharField(max_length=100, unique=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapp.parada')),
            ],
        ),
    ]
