# Generated by Django 4.2.16 on 2026-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_ruta_color_ruta_destino_ruta_origen_aliasparada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(default='Puebla', max_length=100),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(default='Tlaxcala', max_length=100),
        ),
    ]
