# Generated by Django 4.2.16 on 2026-03-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_alter_ruta_destino_alter_ruta_origen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AliasParada',
        ),
    ]
