# Generated by Django 4.2 on 2026-03-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0006_delete_aliasparada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parada',
            old_name='latitud',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='parada',
            old_name='longitud',
            new_name='lng',
        ),
    ]
