# Generated by Django 4.2 on 2026-03-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0007_rename_latitud_parada_lat_rename_longitud_parada_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='sentido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
