# Generated by Django 4.2.16 on 2026-03-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_fecha_creacion_ruta_creada_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='creada_en',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='descripcion',
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.ruta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
