# Generated by Django 4.2.16 on 2026-03-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_parada_rename_creada_en_ruta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='coordenadas',
        ),
    ]
