# Generated by Django 4.2.16 on 2026-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_ruta_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
