# Generated by Django 4.2.16 on 2026-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_ruta_color_ruta_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='ruta',
            name='coordenadas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='color',
            field=models.CharField(default='#3388ff', max_length=20),
        ),
    ]
