# Generated by Django 4.2.16 on 2026-03-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_remove_ruta_descripcion_ruta_coordenadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='coordenadas',
        ),
    ]
