# Generated by Django 4.2.16 on 2026-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_remove_ruta_color_remove_ruta_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='color',
            field=models.CharField(default='#ff0000', max_length=20),
        ),
    ]
