# Generated by Django 4.2.16 on 2026-03-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_ruta_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaparada',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_paradas', to='adminpanel.ruta'),
        ),
    ]
