# Generated by Django 4.2.16 on 2026-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_rutaparada_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='ruta',
            name='paradas',
            field=models.ManyToManyField(through='adminpanel.RutaParada', to='adminpanel.parada'),
        ),
    ]
