# Generated by Django 4.2.16 on 2026-03-04 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_remove_ruta_fecha_creacion_ruta_paradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='coordenadas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
