# Generated by Django 4.2.16 on 2026-03-04 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_ruta_coordenadas_ruta_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
