# Generated by Django 4.2.16 on 2026-03-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_ruta_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_viaje', models.TimeField()),
                ('ultimo_viaje', models.TimeField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_ruta', to='adminpanel.parada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_ruta', to='adminpanel.parada')),
            ],
        ),
    ]
