# Generated by Django 4.2.16 on 2026-03-08 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_horarioruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioruta',
            name='notas',
        ),
        migrations.AddField(
            model_name='horarioruta',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='adminpanel.ruta'),
        ),
    ]
