# Generated by Django 4.2.16 on 2026-03-09 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0014_remove_horarioruta_notas_horarioruta_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('add_parada', 'Agregar Parada'), ('edit_parada', 'Editar Parada'), ('delete_parada', 'Eliminar Parada'), ('add_ruta', 'Agregar Ruta'), ('edit_ruta', 'Editar Ruta'), ('delete_ruta', 'Eliminar Ruta'), ('edit_horario', 'Modificar Horario')], max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
