# Generated by Django 4.2.16 on 2026-03-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_actividadreciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioruta',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='horarioruta',
            name='tarifa',
        ),
        migrations.CreateModel(
            name='TarifaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa_destino', to='adminpanel.parada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa_origen', to='adminpanel.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='adminpanel.ruta')),
            ],
        ),
    ]
