# Generated by Django 4.2.16 on 2026-03-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_remove_horarioruta_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadreciente',
            name='accion',
            field=models.CharField(choices=[('add_parada', 'Agregar Parada'), ('edit_parada', 'Editar Parada'), ('delete_parada', 'Eliminar Parada'), ('add_ruta', 'Agregar Ruta'), ('edit_ruta', 'Editar Ruta'), ('delete_ruta', 'Eliminar Ruta'), ('edit_horario', 'Modificar Horario'), ('add_tarifa', 'Agregar Tarifa'), ('edit_tarifa', 'Editar Tarifa'), ('delete_tarifa', 'Eliminar Tarifa')], max_length=50),
        ),
    ]
