# Generated by Django 4.2.16 on 2026-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_alter_actividadreciente_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='tipo',
            field=models.CharField(choices=[('parada', 'Parada'), ('terminal', 'Terminal')], default='parada', max_length=10),
        ),
    ]
