# Generated by Django 4.2.16 on 2026-03-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_parada_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='horarioruta',
            name='frecuencia',
            field=models.IntegerField(help_text='Frecuencia en minutos'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifaruta',
            unique_together={('ruta', 'origen', 'destino')},
        ),
    ]
