# Generated by Django 4.2.16 on 2026-03-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_remove_parada_tipo_alter_horarioruta_frecuencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioruta',
            options={'ordering': ['ruta', 'origen']},
        ),
        migrations.AlterModelOptions(
            name='parada',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tarifaruta',
            options={'ordering': ['ruta']},
        ),
        migrations.AlterField(
            model_name='horarioruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_destino', to='adminpanel.parada'),
        ),
        migrations.AlterField(
            model_name='horarioruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_origen', to='adminpanel.parada'),
        ),
        migrations.AlterField(
            model_name='rutaparada',
            name='parada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parada_rutas', to='adminpanel.parada'),
        ),
        migrations.AlterField(
            model_name='tarifaruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_destino', to='adminpanel.parada'),
        ),
        migrations.AlterField(
            model_name='tarifaruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_origen', to='adminpanel.parada'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioruta',
            unique_together={('ruta', 'origen', 'destino')},
        ),
        migrations.AlterUniqueTogether(
            name='rutaparada',
            unique_together={('ruta', 'parada')},
        ),
    ]
