# Generated by Django 4.2.16 on 2026-03-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_alter_horarioruta_options_alter_parada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='coordenadas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
