# Generated by Django 4.2.16 on 2026-03-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_alter_ruta_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='coordenadas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
