# Generated by Django 4.2.16 on 2026-03-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_alter_ruta_destino_alter_ruta_origen'),
        ('adminpanel', '0022_alter_ruta_coordenadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='mapapp.parada')),
            ],
        ),
    ]
