# Generated by Django 4.2.16 on 2026-03-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_aliasparada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AliasParada',
        ),
    ]
