# Generated by Django 4.2 on 2026-03-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_delete_aliasparada'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='sentido',
            field=models.CharField(choices=[('ida', 'Ida'), ('vuelta', 'Vuelta'), ('ambos', 'Ambos Sentidos')], default='ambos', max_length=10),
        ),
        migrations.AddField(
            model_name='parada',
            name='tipo',
            field=models.CharField(choices=[('terminal', 'Terminal'), ('principal', 'Parada Principal'), ('comun', 'Parada Común')], default='comun', max_length=20),
        ),
    ]
