# Generated by Django 4.2 on 2026-03-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_parada_sentido_parada_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='sentido',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='tipo',
        ),
    ]
