# Generated by Django 4.2 on 2026-03-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_remove_parada_sentido_remove_parada_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='sentido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
